[platformio]
default_envs = sensor_field1, sensor_field2, bridge, central_controller

[env]
platform = espressif32@6.12.0
framework = arduino
board = esp32-s3-devkitc-1
lib_deps = bblanchon/ArduinoJson@7.2.1
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++17 -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1

[env:sensor_field1]
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
build_flags = ${env.build_flags} -DBOARD_HAS_PSRAM -DSMARTFARM_ROLE_SENSOR=1 -DSMARTFARM_SENSOR_FIELD=1

[env:sensor_field2]
extends = env:sensor_field1
build_flags = ${env.build_flags} -DBOARD_HAS_PSRAM -DSMARTFARM_ROLE_SENSOR=1 -DSMARTFARM_SENSOR_FIELD=2

[env:bridge]
build_flags = ${env.build_flags} -DSMARTFARM_ROLE_BRIDGE=1

[env:central_controller]
build_flags = ${env.build_flags} -DSMARTFARM_ROLE_CENTRAL=1
