[platformio]
default_envs = bridge_usb

[env]
platform = espressif32
framework = arduino
lib_deps = bblanchon/ArduinoJson@^7.2.1
monitor_speed = 115200
upload_speed = 921600

[env:sensor_node]
board = esp32-s3-devkitc-1
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DSMARTFARM_ROLE_SENSOR=1

[env:bridge_usb]
board = freenove_esp32_s3_wroom
build_flags =
    -DSMARTFARM_ROLE_BRIDGE=1

[env:central_led]
board = esp32-s3-devkitc-1
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DSMARTFARM_ROLE_CENTRAL=1
    -DSMARTFARM_VALVE_PIN=48
    -DSMARTFARM_PUMP_PIN=47
