[env:sender_uart]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
build_flags =
    -DLINK_ROLE_SENDER=1
monitor_speed = 115200
upload_speed = 921600

[env:receiver_usb]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_upload.flash_size = 8MB
build_flags =
    -DLINK_ROLE_SENDER=0
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200
upload_speed = 921600

[env:receiver_uart]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
build_flags =
    -DLINK_ROLE_SENDER=0
monitor_speed = 115200
upload_speed = 921600
